FROM ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main

COPY docker/cross/openssl.sh /
RUN bash /openssl.sh linux-x86_64 x86_64-linux-gnu-
ENV OPENSSL_DIR=/openssl \
    OPENSSL_INCLUDE_DIR=/openssl/include \
    OPENSSL_LIB_DIR=/openssl/lib \
    OPENSSL_STATIC=1
