FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main

COPY docker/cross/openssl.sh /
RUN bash /openssl.sh linux-aarch64 aarch64-linux-gnu-
ENV OPENSSL_DIR=/openssl \
    OPENSSL_INCLUDE_DIR=/openssl/include \
    OPENSSL_LIB_DIR=/openssl/lib \
    OPENSSL_STATIC=1
